# Committed configuration for conventional commits

# Disable default checks that conflict with conventional commits
subject_capitalized = false
subject_not_punctuated = true
imperative_subject = false

# Enable conventional commit style
style = "conventional"

# Allowed commit types
allowed_types = [
  "feat",     # New feature
  "fix",      # Bug fix
  "docs",     # Documentation changes
  "perf",     # Performance improvements
  "refactor", # Code refactoring
  "test",     # Adding tests
  "chore",    # Maintenance tasks
  "ci",       # CI/CD changes
  "revert",   # Revert previous commit
]

# Allow optional scope in parentheses
allowed_scopes = []
