[package]
name = "typers"
version = "0.1.0"
edition = "2024"


[lints.clippy]
# Groups
perf = { level = "deny", priority = -1 }
correctness = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

[dependencies]
ratatui = { version = "0.29", features = ["serde"] }
throbber-widgets-tui = "0.8"
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
crossterm = "0.28"
minreq = { version = "2.13", features = ["https", "json-using-serde"] }
directories = "6.0"
strum = { version = "0.27", features = ["derive"] }
