[package]
name = "typers"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
throbber-widgets-tui = "0.8.0"
serde = { version = "1.0", features = ["derive"]}
figment = "0.10"
crossterm = "0.28.1"
minreq = { version = "2.13.2", features = ["https", "json-using-serde"] }
directories = "6.0.0"
