Output demo.gif
Output demo.webm

Set TypingSpeed 115ms
Set Shell "nu"
Set FontSize 24
Set Width 1400
Set Height 1000

Type "octotype"

Sleep 500ms

Enter 1

Sleep 500ms

# Select Mode
Enter 1

Sleep 1s

# Select Source
Enter 1

Sleep 4s

Type "The quick brownfox"

Backspace 3

Type " fox jumps over the lazy dog, testing my typingspeed"

Backspace 5

Type " speed with every leap, but I'll soon catch up. "

Sleep 7s

Ctrl+Q

Sleep 1s
