import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Configuration
  configuration: [{ type: "autogenerated", dirName: "configuration" }],

  // Contributing
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
};

export default sidebars;
