name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: extractions/setup-just@v3
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: just lint
      - name: Build
        run: just build ${{ matrix.target }}
      - name: Run tests
        run: just test ${{ matrix.target }}
