name: Flake Check

on:
  push:
    branches: ["main"]
    paths:
      - 'flake.nix'
      - 'flake.lock'
  pull_request:
    branches: ["main"]
    paths:
      - 'flake.nix'
      - 'flake.lock'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check flake
        run: nix flake check
