name: Release Binary

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_API_TOKEN: ${{ secrets.CARGO_API_TOKEN }}

jobs:
  build:
    name: Build and Publish Rust Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v3
      - name: Check Code
        run: just lint
      - name: Publish Binary
        run: just publish
