name: Update Flake Inputs

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        run: nix flake update

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update flake inputs"
          title: "chore: update flake inputs"
          body: |
            Automated weekly update of Nix flake inputs.

            This PR will auto-merge once all checks pass.
          branch: update-flake-inputs
          delete-branch: true

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
