name: Check Version Updated

on:
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version changed
        run: |
          git fetch origin main
          CURRENT_VERSION=$(grep '^version = ' Cargo.toml | head -1 | cut -d'"' -f2)
          MAIN_VERSION=$(git show origin/main:Cargo.toml | grep '^version = ' | head -1 | cut -d'"' -f2)

          if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
            echo "Error: Version in Cargo.toml has not been updated"
            exit 1
          fi
          echo "Version updated: $MAIN_VERSION -> $CURRENT_VERSION"
